title: SQL Blog
author: Chris Mandragos
email: christopher.n.mandragos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Review new features, best practises, and common issues/errors when developing
  an ETL using SSIS Packages, plain T-SQL, or other tools.

# social links
twitter_username: CMandragos # DO NOT include the @ character, or else the build will fail!
github_username:  MandragonGamer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
